// ============================================================================
// Transcript Types
// ============================================================================

export interface TranscriptLine {
  start: number; // Start time in seconds
  duration: number; // Duration in seconds
  text: string;
}

export interface Chapter {
  title: string;
  start: number;
  thumbnailUrl?: string;
}

export interface CaptionTrack {
  languageCode: string;
  languageName: string;
  baseUrl: string;
  isAutoGenerated: boolean;
  isDefault: boolean;
}

// ============================================================================
// Transcript Result Types (by tier)
// ============================================================================

export type TranscriptSource =
  | 'youtube-captions'
  | 'youtube-auto-generated'
  | 'fallback-partial'
  | 'server-transcription';

export interface TierAResult {
  tier: 'A';
  source: 'youtube-captions' | 'youtube-auto-generated';
  transcript: TranscriptLine[];
  language: string;
  languageName: string;
  availableTracks: CaptionTrack[];
}

export interface TierBResult {
  tier: 'B';
  source: 'fallback-partial';
  description?: string;
  chapters?: Chapter[];
  isPartial: true;
}

export interface TierCResult {
  tier: 'C';
  source: 'server-transcription';
  transcript: TranscriptLine[];
  status: 'processing' | 'complete' | 'error';
  error?: string;
}

export type TranscriptResult = TierAResult | TierBResult | TierCResult;

// ============================================================================
// Page Types
// ============================================================================

export type PageType = 'watch' | 'shorts' | 'other';
export type ViewMode = 'default' | 'theater' | 'fullscreen';

export interface PageState {
  type: PageType;
  mode: ViewMode;
  videoId: string | null;
}

// ============================================================================
// Message Types (Content Script <-> Service Worker)
// ============================================================================

export type MessageType =
  | 'GET_TRANSCRIPT'
  | 'TRANSCRIPT_RESULT'
  | 'TRANSCRIPT_PROCESSING'
  | 'CHANGE_LANGUAGE'
  | 'SUBMIT_TIER_C'
  | 'GET_SETTINGS'
  | 'SETTINGS_RESULT'
  | 'VIDEO_CHANGED';

export interface GetTranscriptMessage {
  type: 'GET_TRANSCRIPT';
  videoId: string;
  preferredLanguage?: string;
}

export interface TranscriptResultMessage {
  type: 'TRANSCRIPT_RESULT';
  videoId: string;
  result: TranscriptResult;
  cached: boolean;
}

export interface TranscriptProcessingMessage {
  type: 'TRANSCRIPT_PROCESSING';
  videoId: string;
}

export interface ChangeLanguageMessage {
  type: 'CHANGE_LANGUAGE';
  videoId: string;
  languageCode: string;
}

export interface SubmitTierCMessage {
  type: 'SUBMIT_TIER_C';
  videoId: string;
}

export interface GetSettingsMessage {
  type: 'GET_SETTINGS';
}

export interface SettingsResultMessage {
  type: 'SETTINGS_RESULT';
  settings: ExtensionSettings;
}

export interface VideoChangedMessage {
  type: 'VIDEO_CHANGED';
  videoId: string;
}

export type Message =
  | GetTranscriptMessage
  | TranscriptResultMessage
  | TranscriptProcessingMessage
  | ChangeLanguageMessage
  | SubmitTierCMessage
  | GetSettingsMessage
  | SettingsResultMessage
  | VideoChangedMessage;

// ============================================================================
// Settings Types
// ============================================================================

export interface ExtensionSettings {
  backendUrl: string | null;
  preferredLanguage: string;
  autoOpen: boolean;
  darkMode: 'auto' | 'light' | 'dark';
  defaultDownloadFormat: 'srt' | 'vtt' | 'txt';
  keyboardShortcutsEnabled: boolean;
}

export const DEFAULT_SETTINGS: ExtensionSettings = {
  backendUrl: null,
  preferredLanguage: 'en',
  autoOpen: false,
  darkMode: 'auto',
  defaultDownloadFormat: 'srt',
  keyboardShortcutsEnabled: true,
};

// ============================================================================
// Cache Types
// ============================================================================

export interface CacheEntry {
  videoId: string;
  result: TranscriptResult;
  timestamp: number;
  ttl: number;
}

export const CACHE_TTL = {
  TIER_A: 24 * 60 * 60 * 1000, // 24 hours
  TIER_B: 1 * 60 * 60 * 1000, // 1 hour (might get captions later)
  TIER_C: 7 * 24 * 60 * 60 * 1000, // 7 days
};

// ============================================================================
// UI State Types
// ============================================================================

export interface UIState {
  isOpen: boolean;
  isLoading: boolean;
  searchQuery: string;
  activeLineIndex: number;
  selectedLanguage: string | null;
}

export type PanelPosition = 'collapsed' | 'expanded';
export type SheetPosition = 'hidden' | 'peek' | 'half' | 'full';

// ============================================================================
// YouTube API Types (partial, for typing responses)
// ============================================================================

export interface YouTubePlayerResponse {
  captions?: {
    playerCaptionsTracklistRenderer?: {
      captionTracks?: YouTubeCaptionTrack[];
    };
  };
  videoDetails?: {
    videoId: string;
    title: string;
    shortDescription: string;
    lengthSeconds: string;
  };
}

export interface YouTubeCaptionTrack {
  baseUrl: string;
  name: { simpleText: string };
  vssId: string;
  languageCode: string;
  kind?: string; // 'asr' for auto-generated
  isTranslatable: boolean;
}

export interface YouTubeTimedText {
  events: YouTubeTimedTextEvent[];
}

export interface YouTubeTimedTextEvent {
  tStartMs: number;
  dDurationMs: number;
  segs?: { utf8: string }[];
}
